# Generated by Django 5.0.2 on 2024-03-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Pub', 'Pub'), ('Drf', 'Drf')], default='Drf', max_length=3),
        ),
    ]
